# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(872, 580)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(10, 10, 601, 521))
        self.textEdit.setObjectName("textEdit")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(620, 10, 241, 521))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.notes_list = QtWidgets.QListWidget(parent=self.verticalLayoutWidget)
        self.notes_list.setObjectName("notes_list")
        self.verticalLayout.addWidget(self.notes_list)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.add_btn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.add_btn.setObjectName("add_btn")
        self.horizontalLayout_5.addWidget(self.add_btn)
        self.del_btn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.del_btn.setObjectName("del_btn")
        self.horizontalLayout_5.addWidget(self.del_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.save_btn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.save_btn.setObjectName("save_btn")
        self.verticalLayout.addWidget(self.save_btn)
        self.label_2 = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.tags_list = QtWidgets.QListWidget(parent=self.verticalLayoutWidget)
        self.tags_list.setObjectName("tags_list")
        self.verticalLayout.addWidget(self.tags_list)
        self.tag_edit = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.tag_edit.setObjectName("tag_edit")
        self.verticalLayout.addWidget(self.tag_edit)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.add_tag_btn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.add_tag_btn.setObjectName("add_tag_btn")
        self.horizontalLayout_6.addWidget(self.add_tag_btn)
        self.del_tag_btn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.del_tag_btn.setObjectName("del_tag_btn")
        self.horizontalLayout_6.addWidget(self.del_tag_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.search_btn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.search_btn.setObjectName("search_btn")
        self.verticalLayout.addWidget(self.search_btn)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 872, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Список Заміток"))
        self.add_btn.setText(_translate("MainWindow", "Додати Замітку"))
        self.del_btn.setText(_translate("MainWindow", "Видалити Замітку"))
        self.save_btn.setText(_translate("MainWindow", "Зберегти Замітку"))
        self.label_2.setText(_translate("MainWindow", "Список тегів"))
        self.tag_edit.setPlaceholderText(_translate("MainWindow", "Введіть назву тега..."))
        self.add_tag_btn.setText(_translate("MainWindow", "Додати теґ"))
        self.del_tag_btn.setText(_translate("MainWindow", "Видалити теґ"))
        self.search_btn.setText(_translate("MainWindow", "Шукати по теґу"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
